### PR TITLE
Use BASE_URL to determine config.json location

### LINKED ISSUE #230: Reloading alert details page is fail
**Issue Summary**
When I try to reload (or refresh, or press F5 or even Ctrl+F5) the page with alert details, I always see an empty page and a popup alert in my browser.

For example, I reload the page:http://192.168.1.25/alerta/alert/68f54758-f190-4557-8b84-bae6947518b4 and as a result, I see the following:
image
And after clicking on the OK button, I see an empty page.

In the web developer console, I see the following error:
```
Error: Network Error
    at t.exports (createError.js:16)
    at XMLHttpRequest.h.onerror (xhr.js:69)
localhost:8080/config:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
createError.js:16 Uncaught (in promise) Error: Network Error
    at t.exports (createError.js:16)
    at XMLHttpRequest.h.onerror (xhr.js:69)
```
So Alerta WEB tries to use an incorrect Alerta endpoint (`localhost:8080` instead `192.168.1.25`). And as I can see, it happens because Alerta UI loads `config.json` from an incorrect place: http://192.168.1.25/alerta/alert/config.json instead http://192.168.1.25/alerta/config.json. So `config.json` is loaded with a relative URL.

This approach with the relative URL leads to errors in some cases so using `BASE_URL` or something should be more reliable.

**Environment**
- OS: Linux
- API version: 7.3.2
- Deployment: self-hosted
- WSGI environment: nginx/gunicorn

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab

- web UI version: 7.3.2
- CLI version: 7.3.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an alert details page
2. Refresh the whole page (press F5)
4. See the above error

**Expected behavior**
I expect no errors in UI

**Additional context**
To solve the problem I use the following Nginx location to load `config.json`:
```
location ~ ^/alerta/(.+/)?config.json$ {
    alias /etc/alerta/config.json;
}
```
Though this solution is working now it cannot be considered as a good solution for all cases.

EDIT: Please, pay attention to prefix `/alerta` in my Nginx location. I use it because I run Alerta UI under the `/alerta` path.

### PR DESCRIPTION
**Pull request by satterly**
Fixes #230

### CODE REVIEW

File: src/services/config.ts [hunk 1]
```diff
@@ -53,8 +53,9 @@ class Config {
   }
 
   getLocalConfig() {
+    const basePath = process.env.BASE_URL != '/' ? process.env.BASE_URL : '.'
```
Comment (vykulakov) [inline src/services/config.ts]: I cannot understand why you use logic like this. It looks too complicated and like you try to preserve the old behaviour with `.get('./config.json')`. But why we should preserve it? The old logic does not work properly and we must use the hack with the location of `config.json`. So I see two options here:
1. leave the old logic and continue using the Nginx hack.
2. use `BASE_URL` in the following manner: `const basePath = process.env.BASE_URL || '.'` (or something like this)

Comment (satterly) [reply src/services/config.ts]: The difficulty is that I have to consider that the web UI is deployed in many different environments, not just one identical to yours. My test environments alone include Heroku, AWS Cloudfront, GitHub pages and running it locally for development. The "old behaviour" works in all these environments and the majority of others.

It is only in environments where a base path other than the default is set that it the hack is required. And the default is '/' not null. See [publicPath config reference](https://cli.vuejs.org/config/#publicpath)

Comment (vykulakov) [reply src/services/config.ts]: As I know the hack is required in all environments and it does not depend on a base path because it fixes reloading the detail page. Reloading does not work because Alerta uses the relative URL to load `config.json` so on the details page the URL looks like `/alert/config.json` instead just `/config.json`. So your PR does not fix this problem. The PR fixes the problem only when we use a custom base path, to be precise.

So I suggest to not merge this change that solves the problem just partially and leave all as is because most of the people should continue using the hack anyway.

Comment (vykulakov) [reply src/services/config.ts]: And I cannot understand why you want to use a relative path here instead of an absolute one that is stored in the `BASE_URL` variable.

File: src/services/config.ts [hunk 2]
```diff
@@ -53,8 +53,9 @@ class Config {
   }
 
   getLocalConfig() {
+    const basePath = process.env.BASE_URL || './'
```
Comment (satterly) [inline src/services/config.ts]: @vykulakov This assumes that a `BASE_URL` always has a trailing slash. This is the same assumption as for `index.html`.

File: src/services/config.ts [hunk 3]
```diff
@@ -53,8 +53,9 @@ class Config {
...
     return this.$http
-      .get('./config.json')
+      .get(`${basePath}config.json`)
```
Comment (satterly) [inline src/services/config.ts]: @vykulakov This assumes that a `BASE_URL` always has a trailing slash. This is the same assumption as for `index.html`.

Comment (vykulakov) [reply src/services/config.ts]: Looks good for me.

File: src/services/config.ts (hunk 2 above)
Comment (vykulakov) [inline src/services/config.ts]: The last question: is it really necessary to have a default value here? I mean this part ` || './'`.

I suppose the `BASE_URL` variable always has a non-null value (at least `/` by default). But don't forget I'm not a Vue developer so I'm just asking you.

Comment (satterly) [reply src/services/config.ts]: Someone could set it to `null` in the config file, I guess. I'm no expert on Vue or webpack either ;)

Comment (vykulakov) [reply src/services/config.ts]: They will have many problems in this case and the bad config path is the smallest of them, though :)

So do you expect that I test this change before it will be merged? Or after, maybe.

Comment (satterly) [reply src/services/config.ts]: I'm happy to merge this, as is.
